[package]
name = "lice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
dialoguer = "0.11.0"
whoami = "1.5.0"
